name: $(Build.BuildId)

# Trigger on push to development
trigger:
- development

pool:
  vmImage: 'Ubuntu-16.04'

# Note: github_pat should be configured as an environment variable in devops
#   -> create github pat here: https://github.com/settings/tokens
#   -> Create environment variable in dev.azure.com under pipelines -> edit (right top) -> variables (right top triple dots) -> called github_pat -> click the lock
variables:
  gh_user: thebillkidy
  gh_repo: thebillkidy.github.io
  gh_pass: $(github_pat)
  gh_email: xavier.geerinck@gmail.com
  gh_auth_header: $(echo -n "${gh_user}:$(github_pat)" | base64);

steps:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azdevops&tabs=schema#checkout
- checkout: none # we are not going to sync sources, we will manually clone
  persistCredentials: false # We disallow setting the persisting, since we want to have a verified push which requires a PAT token

# 1. Setup our local repository and branch that we can work on
- script: git clone https://$(github_pat)@github.com/$(gh_user)/$(gh_repo).git .
  workingDirectory: $(Build.StagingDirectory)
  displayName: "[Git] Clone GitHub Pages Repository"

- script: |
    git config user.email $(gh_email)
    git config user.name $(gh_user)
  displayName: '[Git] Configure User'

# 2. Build our site
- task: UseRubyVersion@0 # See: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azdevops
  displayName: '[Jekyll] Use Ruby >= 2.5'

- script: 'gem install bundler'
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Jekyll] Install Bundler'

- script: 'bundle install'
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Jekyll] Install Jekyll and Dependencies'

- script: 'bundle exec jekyll build -d $(Build.StagingDirectory)'
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Jekyll] Build Jekyll Static Site'

# 3. Create our commit and push it
- script: |
    git add --all;
    git commit -m"Pipelines-Bot: Updated site via $(Build.SourceVersion)";
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Git] Creating commit'

- script: |
    git push origin master;
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Git] Push changes to remote'

# 4. Get GitHub Pages build status
# - script: |
#     gh_user="thebillkidy";
#     gh_pass=$(github_pat);
#     gh_repo="thebillkidy.github.io";
#     auth_pass=$(echo -n "${gh_user}:$(github_pat)" | base64);

#     curl https://api.github.com/repos/${gh_user}/${gh_repo}/pages/builds -i -v \
#     -X POST \
#     -H "Accept: application/vnd.github.mister-fantastic-preview+json" \
#     -H "Authorization: Basic ${auth_pass}"
#   displayName: '[GitHub] Trigger Page Build'

- script: |
    curl https://api.github.com/repos/${gh_user}/${gh_repo}/pages/builds/latest -i -v \
    -X GET \
    -H "Accept: application/vnd.github.mister-fantastic-preview+json" \
    -H "Authorization: Basic $(gh_auth_header)"
  displayName: '[GitHub] Get Page Build Status'
